import type {
  FullTimeData,
  MatchDayData,
  StandingsData,
} from "@/lib/templates/types";

export const FULLTIME_DEFAULTS: FullTimeData = {
  heroPhoto: "/templates/fulltime.jpg",
  date: "18 OCT",
  fieldName: "Estadio Norte",
  matchday: "14",
  season: "2025/26",
  teamA: { logo: null },
  teamB: { logo: null },
  scoreA: 2,
  scoreB: 1,
  scorersA: [{ name: "Da Silva", goals: 1 }, { name: "Okafor", goals: 2 }],
  scorersB: [{ name: "Petit (P)", goals: 1 }],
};

export const MATCHDAY_DEFAULTS: MatchDayData = {
  teamA: { name: "FC Urban", logo: null },
  teamB: { name: "AS Panthère", logo: null },
  dateTime: "Samedi 31 mai · 20h30",
  venue: "Gymnase Municipal — Salle A",
  matchday: "Journée 13",
};

export const STANDINGS_DEFAULTS: StandingsData = {
  title: "Classement — Phase régulière",
  rows: [
    {
      rank: 1,
      teamName: "FC Urban",
      logo: null,
      played: 12,
      wins: 10,
      draws: 1,
      losses: 1,
      gf: 48,
      ga: 18,
      points: 31,
    },
    {
      rank: 2,
      teamName: "AS Panthère",
      logo: null,
      played: 12,
      wins: 9,
      draws: 2,
      losses: 1,
      gf: 42,
      ga: 22,
      points: 29,
    },
    {
      rank: 3,
      teamName: "Olympique 5",
      logo: null,
      played: 12,
      wins: 7,
      draws: 2,
      losses: 3,
      gf: 35,
      ga: 28,
      points: 23,
    },
    {
      rank: 4,
      teamName: "Racing Futsal",
      logo: null,
      played: 12,
      wins: 6,
      draws: 1,
      losses: 5,
      gf: 30,
      ga: 31,
      points: 19,
    },
    {
      rank: 5,
      teamName: "Nova Squad",
      logo: null,
      played: 12,
      wins: 4,
      draws: 3,
      losses: 5,
      gf: 28,
      ga: 33,
      points: 15,
    },
    {
      rank: 6,
      teamName: "Street Kings",
      logo: null,
      played: 12,
      wins: 2,
      draws: 2,
      losses: 8,
      gf: 20,
      ga: 41,
      points: 8,
    },
  ],
};
